development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: job_finder
staging:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: job_finder
production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: job_finder
